services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8085:8000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - DATABASE_URL=sqlite:///data/nhc_tracker.db
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
    networks:
      - nhc-network

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - DATABASE_URL=sqlite:///data/nhc_tracker.db
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 */1 * * *}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
    networks:
      - nhc-network

networks:
  nhc-network:
    driver: bridge
